import type { KeybindingRule } from "./types";

export const DEFAULT_KEYBINDINGS: readonly KeybindingRule[] = [
  { key: "mod+=", command: "canvas.zoomIn", label: "Zoom In" },
  { key: "mod+-", command: "canvas.zoomOut", label: "Zoom Out" },
  { key: "mod+0", command: "canvas.fitView", label: "Fit View" },
  {
    key: "mod+shift+f",
    command: "canvas.fullscreenNode",
    label: "Toggle Fullscreen Mode",
    when: "canvasFocus && !pickerSelected",
  },
  {
    key: "mod+a",
    command: "canvas.selectAll",
    label: "Select All",
    when: "canvasFocus",
  },
  {
    key: "backspace",
    command: "canvas.deleteSelected",
    label: "Delete Selected",
    when: "canvasFocus && !inputFocus",
  },
  {
    key: "delete",
    command: "canvas.deleteSelected",
    label: "Delete Selected",
    when: "canvasFocus && !inputFocus",
  },
  {
    key: "mod+h",
    command: "tiling.createLeft",
    label: "New Terminal Column Left",
    when: "!pickerSelected",
  },
  {
    key: "mod+l",
    command: "tiling.createRight",
    label: "New Terminal Column Right",
    when: "!pickerSelected",
  },
  {
    key: "mod+k",
    command: "tiling.createUp",
    label: "New Terminal Above in Column",
    when: "!pickerSelected",
  },
  {
    key: "mod+j",
    command: "tiling.createDown",
    label: "New Terminal Below in Column",
    when: "!pickerSelected",
  },
  {
    key: "mod+shift+h",
    command: "tiling.insertLeft",
    label: "Insert Column Left",
    when: "!pickerSelected",
  },
  {
    key: "mod+shift+l",
    command: "tiling.insertRight",
    label: "Insert Column Right",
    when: "!pickerSelected",
  },
  {
    key: "mod+shift+k",
    command: "tiling.insertUp",
    label: "Insert Above in Column",
    when: "!pickerSelected",
  },
  {
    key: "mod+shift+j",
    command: "tiling.insertDown",
    label: "Insert Below in Column",
    when: "!pickerSelected",
  },
  {
    key: "mod+left",
    command: "tiling.focusLeft",
    label: "Focus Left",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+right",
    command: "tiling.focusRight",
    label: "Focus Right",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+up",
    command: "tiling.focusUp",
    label: "Focus Up",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+down",
    command: "tiling.focusDown",
    label: "Focus Down",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+shift+left",
    command: "tiling.moveLeft",
    label: "Move to Left Column",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+shift+right",
    command: "tiling.moveRight",
    label: "Move to Right Column",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+shift+up",
    command: "tiling.moveUp",
    label: "Move Up in Column",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+shift+down",
    command: "tiling.moveDown",
    label: "Move Down in Column",
    when: "!pickerSelected && !(browserSelected && inputFocus)",
  },
  {
    key: "mod+shift+o",
    command: "tiling.toggleOverview",
    label: "Toggle Overview",
    when: "canvasFocus",
  },
  {
    key: "mod+shift+b",
    command: "tiling.toggleTabbed",
    label: "Toggle Tabbed Column",
    when: "canvasFocus && !inputFocus && !pickerSelected",
  },
  { key: "mod+shift+t", command: "theme.toggle", label: "Toggle Theme" },
  { key: "mod+shift+p", command: "app.commandPalette" },
  { key: "mod+shift+n", command: "workspace.newCanvas", label: "New Canvas" },
  { key: "mod+o", command: "workspace.openProject", label: "Open Project" },
  {
    key: "mod+shift+w",
    command: "workspace.closeCanvas",
    label: "Close Canvas",
  },
  {
    key: "mod+shift+[",
    command: "workspace.prevCanvas",
    label: "Previous Canvas",
  },
  { key: "mod+shift+]", command: "workspace.nextCanvas", label: "Next Canvas" },
  { key: "mod+1", command: "workspace.project1", label: "Project 1" },
  { key: "mod+2", command: "workspace.project2", label: "Project 2" },
  { key: "mod+3", command: "workspace.project3", label: "Project 3" },
  { key: "mod+4", command: "workspace.project4", label: "Project 4" },
  { key: "mod+5", command: "workspace.project5", label: "Project 5" },
  { key: "mod+6", command: "workspace.project6", label: "Project 6" },
  { key: "mod+7", command: "workspace.project7", label: "Project 7" },
  { key: "mod+8", command: "workspace.project8", label: "Project 8" },
  { key: "mod+9", command: "workspace.project9", label: "Project 9" },
];
