// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface TerminalBridge {
  onData: (callback: (id: string, data: string) => void) => () => void;
  onExit: (
    callback: (id: string, exitCode: number, signal: number) => void,
  ) => () => void;
}

interface WebviewBridge {
  registerWebview: (webContentsId: number) => void;
  unregisterWebview: (webContentsId: number) => void;
  onEscape: (callback: (webContentsId: number) => void) => () => void;
}

interface Window {
  terminalBridge: TerminalBridge;
  webviewBridge: WebviewBridge;
}
